<html><head><title>Photo Album - Reports</title>
%STYLESHEET%
</head>
<body bgcolor="fFfFfF">

<h2>Photo Album Reporting</h2>

<ul>
    <li><a href="%SELF_URI%?func=repmostpopular">Popular Images</a></li>
    <li><a href="%SELF_URI%?func=repmostpopular30d">Popular Images
		(last 30 days)</a></li>
    <li><a href="%SELF_URI%?func=repmostcommonip">Common IP Addresses</a></li>
    <li><a href="%SELF_URI%?func=repauth">Auth Report</a></li>
</ul>

</body>
</html>
