// Copyright (c) 2001  SPY internetworking <dustin@spy.net>
// Written by Dustin's SQL generator version $Revision: 1.6 $
//
// $Id: FindImagesByComments.java,v 1.6 2002/06/03 06:49:21 dustin Exp $

package net.spy.photo.sp;

import java.sql.Types;
import java.sql.Connection;
import java.sql.SQLException;
import net.spy.db.DBSQL;
import net.spy.SpyConfig;

/**
 * 
 * Get a list of images based on when comments were posted for them.
 *
 * <p>
 *
 * Generated by SPGen version $Revision: 1.6 $ on Sun Jun 02 23:41:23 PDT 2002
 *
 * <p>
 *
 * <b>SQL Query</b>
 *
 * <ul>
 * <pre>
 * select
 * 	c.comment_id, c.photo_id, c.note, c.ts, c.remote_addr, c.wwwuser_id,
 * 	latestcomment(c.photo_id) as cts
 * from
 * 	album a, commentary c, wwwacl acl
 * where
 * 	a.id=c.photo_id
 * 	and acl.userid = ?
 * 	and acl.cat = a.cat
 * order by
 * 	cts desc,
 * 	c.ts desc
 * </pre>
 * </ul>
 *
 * <b>Required Parameters</b> * <ul>
 * <li>user_id - INTEGER -  The user who wants to know.</li>
 * </ul>
 *
 * <p>
 *
 *
 * <b>Optional Parameters</b> * <ul>
 *  <li><i>none</i></li>
 * </ul>
 *
 * <p>
 *
 */

public class FindImagesByComments extends DBSQL {

	public FindImagesByComments(SpyConfig conf) throws SQLException {
		// Super constructor
		super(conf);
		spinit();
	}

	public FindImagesByComments(Connection conn) throws SQLException {
		// Super constructor
		super(conn);
		spinit();
	}

	private void spinit() {
		// Set the SQL
		setQuery(""
			+ "select\n"
			+ "	c.comment_id, c.photo_id, c.note, c.ts, c.remote_addr, c.wwwuser_id,\n"
			+ "	latestcomment(c.photo_id) as cts\n"
			+ "from\n"
			+ "	album a, commentary c, wwwacl acl\n"
			+ "where\n"
			+ "	a.id=c.photo_id\n"
			+ "	and acl.userid = ?\n"
			+ "	and acl.cat = a.cat\n"
			+ "order by\n"
			+ "	cts desc,\n"
			+ "	c.ts desc\n"
			);

		// Set the required parameters.
		setRequired("user_id", Types.INTEGER);
	}

}
